/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenges;

public class Library {
    public boolean someLibraryMethod() {
        System.out.println("hi");

        return true;

        
    }

}
